

room_descriptions = [
    "You enter a grand hall lined with faded banners and cracked marble pillars.",
    "This chamber is filled with the scent of old parchment and shelves of dusty tomes.",
    "A flickering blue light illuminates a circular room with a mosaic floor.",
    "You find yourself in a damp cellar, water dripping steadily from the ceiling.",
    "Broken armor and shattered shields litter the floor of this abandoned armory.",
    "A spiral staircase winds up the center of this narrow, torch-lit tower.",
    "The walls here are covered in strange, glowing runes that pulse softly.",
    "You step into a greenhouse overrun with tangled vines and exotic plants.",
    "This room is eerily silent, with a single, ancient statue standing in the center.",
    "A cold draft blows through a corridor lined with barred prison cells.",
    "You are in a kitchen, pots and pans scattered as if someone left in a hurry.",
    "A low mist clings to the floor of this crypt, where stone coffins line the walls.",
    "This chamber is filled with gears and levers, the remnants of a forgotten machine.",
    "You enter a lavish bedroom, the bed draped in velvet and a cracked mirror on the wall.",
    "A circular chamber with a domed ceiling, painted with faded constellations."
]



all_items = [
    "map",
    "lantern",
    "torch",
    "sword",
    "shield",
    "goldcoin",
    "bread",
    "turtle",
    "toilet",
    "sweet_roll",
    "cheesewheel",
    "old boot",
    "fishing rod",
    "chair",
    "goldfish",
    "magic wand",
    "rusty key",
    "healing potion",
    "silver dagger",
    "ancient coin",
    "magic scroll",
    "rope",
    "emerald ring",
    "leather boots",
    "iron helmet",
    "mysterious amulet",
    "crystal orb",
    "broken shield",
    "lockpick set",
    "vial of poison",
    "map fragment",
    "enchanted cloak",
    "dragon scale",
    "goblet of wine",
    "ancient tome",
    "bag of gems",
    "silver flute",
    "potion of invisibility",
    "cursed ring",
    "elven arrow",
    "wizard's hat",
    "arrow"
]